### ISSUE TITLE
Test on Win8.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Joeschmoh/dqdos-dvorak-qwerty-keyboard-controller#5]
```
Currently only tested on Win7 systems. Needs to be tested on Win8 and with Win8 
"Store" apps.
```

Original issue reported on code.google.com by `DerickOS...@gmail.com` on 15 Jan 2015 at 6:27

**Comment by Joeschmoh** [comment]
I have run this on Windows 8.1 and on Server 2012 R2. It worked the same as Win7 on both.
